name: release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout main
        uses: actions/checkout@v4

      - name: install rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}
      
      - name: setup rokit
        shell: bash
        run: rokit init

      - name: trust lune
        shell: bash
        run: rokit trust lune-org/lune
      
      - name: trust darklua
        shell: bash
        run: rokit trust seaofvoices/darklua

      - name: install lune
        shell: bash
        run: rokit add lune-org/lune
      
      - name: install darklua
        shell: bash
        run: rokit add seaofvoices/darklua

      - name: run release script
        shell: bash
        run: lune run .lune/release.luau

      - name: get release from configuration.luau
        id: read_luau_version
        shell: bash
        run: |
          version=$(lune run .lune/getVersion.luau)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.read_luau_version.outputs.version }}
          tag_name: ${{ steps.read_luau_version.outputs.version }}
          files: |
            releases/**
          draft: true
