name: release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout main
        uses: actions/checkout@v4

      - name: install rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ github.token }}
      
      - name: setup rokit
        shell: bash
        run: rokit init

      - name: trust lune
        shell: bash
        run: rokit trust lune-org/lune

      - name: install lune
        shell: bash
        run: rokit add lune-org/lune

      - name: run release script
        shell: bash
        run: lune run .lune/release.luau

      - name: get release from configuration.luau
        id: read_luau_version
        shell: bash
        run: |
          version=$(lua - <<'LUA'
          local cfg = dofile("src/configuration.luau")
          local v = cfg.currentVersion
          print(string.format("%s.%s.%s", v.major, v.minor, v.patch))
          LUA
          )
          echo "value=$version" >> $GITHUB_OUTPUT

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.read_luau_version.outputs.value }}
          tag_name: ${{ steps.read_luau_version.outputs.value }}
          draft: true
